package com.privacy2345.droidprivacy.util;


import android.text.TextUtils;

import java.util.HashMap;
import java.util.Map;

/**
 * 调用主体判断工具类，通过堆栈中的包名识别调用者，不一定准确
 *
 * @author : zhongjy@2345.com
 */
public class CallerIdentificationUtil {
    public static Map<String, String> sdkInfoMap = new HashMap<>();

    static {
        sdkInfoMap.put("com.maxthon.main", "遨游代理");
        sdkInfoMap.put("com.maxthon.proxy.", "遨游代理");
        sdkInfoMap.put("com.chosen.kf5sdk", "逸创云客服");
        sdkInfoMap.put("com.xunlei.download.", "迅雷下载");
        sdkInfoMap.put("com.xunlei.yueyangvod", "迅雷vodplayer");
        sdkInfoMap.put("com.cmcm.cmgame", "豹趣小游戏");
        sdkInfoMap.put("com.cmcm.gamemoney_sdk", "豹趣小游戏");
        sdkInfoMap.put("com.google.android.gms.analytics", "谷歌统计");
        sdkInfoMap.put("com.google.analytics", "谷歌统计");
        sdkInfoMap.put("com.google.android.gms", "谷歌服务框架");
        sdkInfoMap.put("com.google.android.play.billingclient.", "谷歌应用内购");
        sdkInfoMap.put("com.google.android.gms.ads.purchase.InAppPurchaseActivity", "谷歌应用内购");
        sdkInfoMap.put("com.google.android.gms.maps", "谷歌地图");
        sdkInfoMap.put("com.google.android.geo.API_KEY", "谷歌地图");
        sdkInfoMap.put("com.google.android.maps", "谷歌地图");
        sdkInfoMap.put("com.google.android.tts.", "谷歌 文字转语音");
        sdkInfoMap.put("android.speech.tts", "谷歌 文字转语音");
        sdkInfoMap.put("com.google.sample.", "谷歌 sample");
        sdkInfoMap.put("com.google.android.datatransport", "谷歌 datatransport");
        sdkInfoMap.put("com.google.vr.", "谷歌 VR");
        sdkInfoMap.put("com.google.firebase.", "谷歌 FireBase");
        sdkInfoMap.put("com.google.vrtoolkit.cardboard", "谷歌 Cardboard");
        sdkInfoMap.put("com.zhuge.analysis", "诸葛IO");
        sdkInfoMap.put("com.iflytek", "讯飞开放平台");
        sdkInfoMap.put("io.rong.imlib", "融云IM");
        sdkInfoMap.put("io.rong.imkit", "融云IM");
        sdkInfoMap.put("com.qingting.", "蜻蜓FM");
        sdkInfoMap.put("qingting.qingting.fm", "蜻蜓FM");
        sdkInfoMap.put("qingting.open.appid", "蜻蜓FM");
        sdkInfoMap.put("com.pgyersdk", "蒲公英内测");
        sdkInfoMap.put("com.megvii.zhimasdk", "芝麻认证");
        sdkInfoMap.put("cooperation.qqreader", "腾讯阅读");
        sdkInfoMap.put("com.tencent.stat", "腾讯统计");
        sdkInfoMap.put("com.tencent.gps.cloudgame", "腾讯游戏");
        sdkInfoMap.put("com.tencent.game", "腾讯游戏");
        sdkInfoMap.put("com.tencent.gamecenter", "腾讯游戏");
        sdkInfoMap.put("cooperation.smartdevice", "腾讯智能设备");
        sdkInfoMap.put("com.tencent.device.", "腾讯智能设备");
        sdkInfoMap.put("com.tencent.ipai", "腾讯时光");
        sdkInfoMap.put("com.tencent.tbs", "腾讯TBS");
        sdkInfoMap.put("com.tencent.smtt.sdk", "腾讯TBS");
        sdkInfoMap.put("com.tencent.android.vivopush", "腾讯推送");
        sdkInfoMap.put("com.tencent.android.hwpush", "腾讯推送");
        sdkInfoMap.put("com.tencent.android.xg.", "腾讯推送");
        sdkInfoMap.put("com.tencent.tpns", "腾讯推送");
        sdkInfoMap.put("com.tencent.android.mipush", "腾讯推送");
        sdkInfoMap.put("com.tencent.android.mzpush", "腾讯推送");
        sdkInfoMap.put("com.tencent.component.thirdpartypush", "腾讯推送");
        sdkInfoMap.put("com.tencent.weibo.sdk", "腾讯微博");
        sdkInfoMap.put("com.qq.AppService.", "腾讯应用助手");
        sdkInfoMap.put("com.connector.qq.AppService", "腾讯应用助手");
        sdkInfoMap.put("com.tencent.map.geolocation", "腾讯地图定位");
        sdkInfoMap.put("com.tencent.map", "腾讯地图");
        sdkInfoMap.put("com.tencent.tencentmap", "腾讯地图");
        sdkInfoMap.put("com.tencent.picker.", "腾讯图片选择");
        sdkInfoMap.put("cooperation.comic", "腾讯动漫");
        sdkInfoMap.put("com.tencent.android.tpush.service.XGVipPushService", "腾讯信鸽推送收费版");
        sdkInfoMap.put("com.tencent.android.xg.vip.", "腾讯信鸽推送收费版");
        sdkInfoMap.put("com.tencent.rdm.uuid", "腾讯信鸽推送");
        sdkInfoMap.put("com.tencent.android.tpush", "腾讯信鸽推送");
        sdkInfoMap.put("com.tencent.qalsdk", "腾讯云通信");
        sdkInfoMap.put("com.tencent.qalsdk.service", "腾讯云通信");
        sdkInfoMap.put("com.tencent.captchasdk", "腾讯云滑块验证码");
        sdkInfoMap.put("com.tencent.msdk.dns", "腾讯云智营防劫持");
        sdkInfoMap.put("com.tencent.xiaowei.sdk", "腾讯云小薇");
        sdkInfoMap.put("com.tencent.feedback.", "腾讯云反馈");
        sdkInfoMap.put("com.tencent.iot", "腾讯云Iot");
        sdkInfoMap.put("com.tencent.cloud", "腾讯云");
        sdkInfoMap.put("com.tencent.qbardemo.", "腾讯qq扫一扫");
        sdkInfoMap.put("com.tencent.mtt.browser.push.", "腾讯X5浏览服务推送");
        sdkInfoMap.put("com.tencent.xweb", "腾讯X5Web");
        sdkInfoMap.put("com.tencent.smtt.", "腾讯X5Web");
        sdkInfoMap.put("com.tencent.mtt.", "腾讯X5Web");
        sdkInfoMap.put("com.tencent.webview", "腾讯X5Web");
        sdkInfoMap.put("com.tencent.tinker", "腾讯Tinker");
        sdkInfoMap.put("com.tme.component", "腾讯TME live");
        sdkInfoMap.put("com.tme.mlive.", "腾讯TME live");
        sdkInfoMap.put("com.tencent.tmassistantagentsdk", "腾讯TMAssistant");
        sdkInfoMap.put("com.tencent.tmassistantsdk.downloadservice", "腾讯TMAssistant");
        sdkInfoMap.put("cooperation.qwallet.", "腾讯QQ钱包");
        sdkInfoMap.put("com.tencent.mobileqq.activity.qwallet.", "腾讯QQ钱包");
        sdkInfoMap.put("com.tencent.midas.qq.APReidasQQWalletActivity", "腾讯QQ钱包");
        sdkInfoMap.put("com.tencent.midas.", "腾讯QQ钱包");
        sdkInfoMap.put("com.tencent.qqmail.", "腾讯QQ邮箱");
        sdkInfoMap.put("cooperation.qzone.", "腾讯QQ空间");
        sdkInfoMap.put("com.tencent.qqconnect", "腾讯QQ互联");
        sdkInfoMap.put("com.tencent.tauth", "腾讯QQ互联");
        sdkInfoMap.put("com.tencent.connect", "腾讯QQ互联");
        sdkInfoMap.put("com.tencent.mid.api.MidProvider", "腾讯MTA");
        sdkInfoMap.put("com.mta.checker.", "腾讯MTA");
        sdkInfoMap.put("com.tencent.bigdata", "腾讯MQTT");
        sdkInfoMap.put("com.tencent.bigdata.mqttchannel", "腾讯MQTT");
        sdkInfoMap.put("dov.com.qq.", "腾讯Dov");
        sdkInfoMap.put("com.tencent.bugly", "腾讯Bugly");
        sdkInfoMap.put("com.tencent.wifisdk", "腾讯 wifi");
        sdkInfoMap.put("com.tencent.pangu", "腾讯 pangu");
        sdkInfoMap.put("com.tencent.moai.", "腾讯 moai");
        sdkInfoMap.put("moai.patch.", "腾讯 moai");
        sdkInfoMap.put("moai.ocr.", "腾讯 moai");
        sdkInfoMap.put("moai.daemon.", "腾讯 moai");
        sdkInfoMap.put("com.tencent.webnet", "腾讯 WebNet");
        sdkInfoMap.put("com.tencent.wns.", "腾讯 WNS");
        sdkInfoMap.put("com.sdk.mobile.manager.login.cucc", "联通登录");
        sdkInfoMap.put("com.umpay.creditcard.android", "联动优势");
        sdkInfoMap.put("com.meiqia.meiqiasdk.", "美洽移动应用");
        sdkInfoMap.put("com.meiqia.core", "美洽移动应用");
        sdkInfoMap.put("com.meitu.mp.sdk", "美图");
        sdkInfoMap.put("com.meituan.hydra", "美团hydra");
        sdkInfoMap.put("com.netease.epay.", "网易支付");
        sdkInfoMap.put("com.netease.pushservice.", "网易推送");
        sdkInfoMap.put("com.cmic.sso.", "移动登录");
        sdkInfoMap.put("mm.sms.purchasesdk.", "移动SDK支付");
        sdkInfoMap.put("mm.purchasesdk", "移动SDK支付");
        sdkInfoMap.put("com.sensorsdata.analytics.", "神策数据");
        sdkInfoMap.put("com.baidu.wallet", "百度钱包");
        sdkInfoMap.put("com.baidu.poly", "百度钱包");
        sdkInfoMap.put("com.baidu.paysdk", "百度钱包");
        sdkInfoMap.put("com.baidu.android.pay", "百度钱包");
        sdkInfoMap.put("com.baidu.wallet.paysdk", "百度钱包");
        sdkInfoMap.put("com.baidu.tts.", "百度语音");
        sdkInfoMap.put("com.baidu.autoupdatesdk", "百度自动更新");
        sdkInfoMap.put("com.baidu.mobstat", "百度移动统计");
        sdkInfoMap.put("com.baidu.mobads", "百度移动推广");
        sdkInfoMap.put("com.baidu.gamesdk", "百度游戏");
        sdkInfoMap.put("com.baidu.haotian.", "百度昊天");
        sdkInfoMap.put("com.baidu.sofire", "百度昊天");
        sdkInfoMap.put("com.baidu.techain", "百度慧推");
        sdkInfoMap.put("com.baidu.platformsdk", "百度开发者平台");
        sdkInfoMap.put("com.baidu.location", "百度定位");
        sdkInfoMap.put("com.duoku.platform", "百度多酷");
        sdkInfoMap.put("com.duoku.platform.push", "百度多酷");
        sdkInfoMap.put("com.baidu.mapapi", "百度地图");
        sdkInfoMap.put("com.baidu.cesium", "百度地图");
        sdkInfoMap.put("com.baidu.cesium.ver", "百度地图");
        sdkInfoMap.put("com.baidu.voicerecognition.android", "百度云语音");
        sdkInfoMap.put("com.baidu.android.pushservice", "百度云推送");
        sdkInfoMap.put("com.baidu.android.imsdk", "百度云");
        sdkInfoMap.put("com.baidu.cloudsdk", "百度云");
        sdkInfoMap.put("com.baidu.webkit.sdk", "百度webkit");
        sdkInfoMap.put("com.baidu.swan", "百度swan");
        sdkInfoMap.put("com.baidu.helios", "百度helios");
        sdkInfoMap.put("com.baidu.titan.", "百度Titan");
        sdkInfoMap.put("com.baidu.sapi2", "百度SAP");
        sdkInfoMap.put("com.baidu.pyramid", "百度Pyramid");
        sdkInfoMap.put("com.baidu.gpt.", "百度GreedyPorter(GPT)");
        sdkInfoMap.put("com.baidu.lbsapi", "百度Android全景");
        sdkInfoMap.put("com.baidu.ufosdk", "百度 Ufo");
        sdkInfoMap.put("com.ipaynow.plugin", "现在支付");
        sdkInfoMap.put("com.hyphenate.push.", "环信推送");
        sdkInfoMap.put("com.easemob.chat.", "环信坐席端");
        sdkInfoMap.put("com.easemob.videocall", "环信坐席端");
        sdkInfoMap.put("com.easemob.kefu.", "环信坐席端");
        sdkInfoMap.put("com.hyphenate.chat.", "环信坐席端");
        sdkInfoMap.put("com.hyphenate.liveroom", "环信 TC-IM");
        sdkInfoMap.put("com.hyphenate.easeui", "环信 EaseUI");
        sdkInfoMap.put("com.iapppay", "爱贝云计费");
        sdkInfoMap.put("com.yixia.", "炫一下");
        sdkInfoMap.put("com.sdu.didi.openapi", "滴滴出行");
        sdkInfoMap.put("com.taobao.agoo", "淘宝推送");
        sdkInfoMap.put("com.taobao.accs.", "淘宝推送");
        sdkInfoMap.put("com.taobao.taobao.scancode.", "淘宝扫一扫");
        sdkInfoMap.put("com.taobao.android.tlog.", "淘宝 tlog");
        sdkInfoMap.put("com.taobao.android.minivideo.", "淘宝 minivideo");
        sdkInfoMap.put("com.taobao.android.miniimage", "淘宝 miniimage");
        sdkInfoMap.put("android.taobao.atlas.", "淘宝 Atlas");
        sdkInfoMap.put("com.bangcle.antihijack.", "梆梆 防劫持");
        sdkInfoMap.put("cn.jpush.yyb.", "极光推送");
        sdkInfoMap.put("cn.jpush.client", "极光推送");
        sdkInfoMap.put("cn.jpush.reactnativejpush.", "极光推送");
        sdkInfoMap.put("cn.jpush.android.ui.Push", "极光推送");
        sdkInfoMap.put("cn.jpush.android", "极光推送");
        sdkInfoMap.put("cn.jpush.android.api", "极光推送");
        sdkInfoMap.put("cn.jpush.", "极光推送");
        sdkInfoMap.put("cn.jiguang", "极光推送");
        sdkInfoMap.put("com.youzan.mobile", "有赞");
        sdkInfoMap.put("com.baofeng.mojing.sdk.", "暴风魔镜");
        sdkInfoMap.put("com.eguan.drivermonitor", "易观方舟");
        sdkInfoMap.put("com.eguan.monitor", "易观方舟");
        sdkInfoMap.put("com.yeepay.android.plugin", "易宝支付");
        sdkInfoMap.put("yxapi.AppRegister", "易信");
        sdkInfoMap.put("im.yixin.sdk", "易信");
        sdkInfoMap.put("yxapi.YXEntryActivity", "易信");
        sdkInfoMap.put("com.megvii.meglive_sdk", "旷视人脸认证");
        sdkInfoMap.put("everphoto.component.", "时光相册");
        sdkInfoMap.put("everphoto.", "时光相册");
        sdkInfoMap.put("com.sina.push", "新浪微博开放平台");
        sdkInfoMap.put("com.sina.weibo.sdk", "新浪微博开放平台");
        sdkInfoMap.put("com.alipay.sdk.auth", "支付宝支付");
        sdkInfoMap.put("com.alipay.android.app.pay", "支付宝支付");
        sdkInfoMap.put("com.alipay.sdk", "支付宝支付");
        sdkInfoMap.put("com.alipay.sdk.app", "支付宝支付");
        sdkInfoMap.put("com.alipay.mobile.scan.", "支付宝扫一扫");
        sdkInfoMap.put("com.alipay.mobile.scansdk.", "支付宝扫一扫");
        sdkInfoMap.put("com.alibaba.alipay", "支付宝开放平台");
        sdkInfoMap.put("com.alipay.android.app.", "支付宝开放平台");
        sdkInfoMap.put("com.alipay.android.app.sdk", "支付宝开放平台");
        sdkInfoMap.put("com.alipay.android.mini", "支付宝开放平台");
        sdkInfoMap.put("com.alipay.mobile.tinyappcustom", "支付宝小程序");
        sdkInfoMap.put("com.alibaba.sdk.android.webview.", "支付宝 Nebula");
        sdkInfoMap.put("com.alipay.android.nebulaapp.", "支付宝 Nebula");
        sdkInfoMap.put("com.sogou.speech.", "搜狗语音云");
        sdkInfoMap.put("com.sogou.passportsdk", "搜狗passport");
        sdkInfoMap.put("com.skymobi.pay", "指易付");
        sdkInfoMap.put("cmbapi.CMBApiEntryActivity", "招商一网通支付");
        sdkInfoMap.put("com.cmbchina.pb.", "招商一网通支付");
        sdkInfoMap.put(".CMBApiEntryActivity", "招商一网通支付");
        sdkInfoMap.put("com.lkl.pay.", "拉卡拉支付");
        sdkInfoMap.put("com.sdklm.shoumeng.", "手盟");
        sdkInfoMap.put("cn.wemart.sdk", "微猫");
        sdkInfoMap.put("com.bx.pay", "微派支付");
        sdkInfoMap.put("com.tencent.mm.sdk", "微信支付");
        sdkInfoMap.put(".BCWechatPaymentActivity", "微信支付");
        sdkInfoMap.put(".wxapi.WXPayEntryActivity", "微信支付");
        sdkInfoMap.put("wxapi.WXEntryActivity", "微信支付");
        sdkInfoMap.put("com.tencent.mm.plugin.scanner", "微信扫一扫");
        sdkInfoMap.put("com.tencent.wxpay.imagefacesign.", "微信刷脸支付");
        sdkInfoMap.put("com.tencent.wxpayface.", "微信刷脸支付");
        sdkInfoMap.put("com.downjoy.", "当乐游戏开放平台");
        sdkInfoMap.put("master.flame.danmaku", "开源弹幕引擎·烈焰弹幕使");
        sdkInfoMap.put("com.ccb.pay.loongpay", "建行龙支付");
        sdkInfoMap.put("com.ccb.loongwealth", "建行龙支付");
        sdkInfoMap.put("adups.smartdevice.fota", "广升(Adups):FOTA升级");
        sdkInfoMap.put("com.xiaomi.push", "小米推送");
        sdkInfoMap.put(".MiPUSH", "小米推送");
        sdkInfoMap.put("com.xiaomi.mipush", "小米推送");
        sdkInfoMap.put("com.xiaomi.market.sdk", "小米应用商店");
        sdkInfoMap.put("com.xiaomi.accounts", "小米帐号开放平台");
        sdkInfoMap.put("com.xiaomi.account.openauth", "小米帐号开放平台");
        sdkInfoMap.put("com.xiaomi.passport", "小米 passport");
        sdkInfoMap.put("com.mi.dlabs.component", "小米 VR");
        sdkInfoMap.put("com.xiaomi.vr.", "小米 VR");
        sdkInfoMap.put("com.mi.dlabs.vr.", "小米 VR");
        sdkInfoMap.put("com.avl.engine.", "安天 AVL");
        sdkInfoMap.put(".AVLScanService", "安天 AVL");
        sdkInfoMap.put("cn.com.chinatelecom.account.", "天翼账号");
        sdkInfoMap.put("com.dianping.base.push", "大众点评推送");
        sdkInfoMap.put("com.daimajia.slider.library", "图片选择 & 图片预览 & 图片加载相关");
        sdkInfoMap.put("com.bumptech.glide", "图片选择 & 图片预览 & 图片加载相关");
        sdkInfoMap.put("de.hdodenhof.circleimageview", "图片选择 & 图片预览 & 图片加载相关");
        sdkInfoMap.put("me.iwf.photopicker", "图片选择 & 图片预览 & 图片加载相关");
        sdkInfoMap.put("in.srain.cube", "图片选择 & 图片预览 & 图片加载相关");
        sdkInfoMap.put("com.dmcbig.mediapicker", "图片选择 & 图片预览 & 图片加载相关");
        sdkInfoMap.put("com.darsh.multipleimageselect.", "图片选择 & 图片预览 & 图片加载相关");
        sdkInfoMap.put("com.ximalaya.ting.android.opensdk", "喜马拉雅FM");
        sdkInfoMap.put("com.networkbench.com", "听云");
        sdkInfoMap.put("com.dingdone.", "叮当APP自助生成平台");
        sdkInfoMap.put("com.efs.sdk", "友盟com.efs");
        sdkInfoMap.put("com.umeng.update", "友盟自动更新");
        sdkInfoMap.put("com.umeng.analytics", "友盟统计分析平台");
        sdkInfoMap.put("com.umeng.common", "友盟组件");
        sdkInfoMap.put("com.umeng.socialize", "友盟社会化组件");
        sdkInfoMap.put("com.umeng.analytics.game", "友盟游戏统计分析");
        sdkInfoMap.put("com.umeng.message", "友盟推送");
        sdkInfoMap.put("com.feedback.ui", "友盟反馈");
        sdkInfoMap.put("com.umeng.fb", "友盟反馈");
        sdkInfoMap.put("com.mobclick.android.UmengFeedback", "友盟反馈");
        sdkInfoMap.put("com.huawei.hms.activity", "华为账户登录认证");
        sdkInfoMap.put("com.huawei.hwid20", "华为游戏中心");
        sdkInfoMap.put("com.huawei.pay.ui", "华为支付");
        sdkInfoMap.put("com.huawei.agconnect.core", "华为推送");
        sdkInfoMap.put("com.huawei.android.pushselfshow", "华为推送");
        sdkInfoMap.put("com.huawei.push.", "华为推送");
        sdkInfoMap.put("com.huawei.updatesdk", "华为推送");
        sdkInfoMap.put("com.huawei.android.pushagent", "华为推送");
        sdkInfoMap.put("com.huawei.intent.action.PUSH_STATE", "华为推送");
        sdkInfoMap.put("com.huawei.intent.action.PUSH", "华为推送");
        sdkInfoMap.put("com.huawei.android.hms.agent", "华为HMS");
        sdkInfoMap.put("com.huawei.hms.client", "华为HMS");
        sdkInfoMap.put("com.huawei.hms", "华为HMS");
        sdkInfoMap.put("com.huawei.hms.aaid", "华为HMS");
        sdkInfoMap.put("com.huawei.hms.support.api.push", "华为HMS");
        sdkInfoMap.put("com.huawei.hms.update", "华为HMS");
        sdkInfoMap.put("com.huawei.hms.support.api.push.PushEventReceiver", "华为HMS");
        sdkInfoMap.put("com.huawei.ar.engine", "华为 AR Engine");
        sdkInfoMap.put("com.chuanglan.shanyan_sdk", "创蓝闪验");
        sdkInfoMap.put("com.bigkoo.pickerview", "仿iOS的PickerView控件");
        sdkInfoMap.put("com.swwx.facesdk", "人脸识别");
        sdkInfoMap.put("com.renn.rennsdk.oauth", "人人网登录");
        sdkInfoMap.put("com.jdpay.paymentcode", "京东支付");
        sdkInfoMap.put("com.jd.lib.jdpaygeneral", "京东支付");
        sdkInfoMap.put("com.jdpaysdk.payment", "京东支付");
        sdkInfoMap.put("com.jd.lib.jdpaysdk", "京东支付");
        sdkInfoMap.put("com.jdpaysdk.author", "京东支付");
        sdkInfoMap.put("com.wangyin.payment.jdpaysdk", "京东支付");
        sdkInfoMap.put("com.jingdong.jdpush_new", "京东推送");
        sdkInfoMap.put("com.kepler.jd.", "京东开普勒");
        sdkInfoMap.put("com.letv.lepaysdk", "乐视支付");
        sdkInfoMap.put("com.le.legamesdk", "乐视手游");
        sdkInfoMap.put("com.letvcloud.cmf", "乐视云");
        sdkInfoMap.put("com.hpplay.sdk", "乐播投屏");
        sdkInfoMap.put("com.cmcc.aoe", "中国移动 AOE");
        sdkInfoMap.put("com.getui.gtc", "个推一键登录");
        sdkInfoMap.put("com.geetest.onelogin", "个推一键登录");
        sdkInfoMap.put("com.igexin.download", "个推");
        sdkInfoMap.put("com.g.gysdk", "个推");
        sdkInfoMap.put("com.igexin.getuiext", "个推");
        sdkInfoMap.put("com.igexin.sdk", "个推");
        sdkInfoMap.put("com.wanpu.pay", "万普支付");
        sdkInfoMap.put("tv.xiaoka.base", "一直播");
        sdkInfoMap.put("tv.xiaoka.weibo", "一直播");
        sdkInfoMap.put("tv.xiaoka.publish", "一直播");
        sdkInfoMap.put("tv.xiaoka.live", "一直播");
        sdkInfoMap.put("tv.xiaoka.play", "一直播");
        sdkInfoMap.put("net.lingala.zip4j", "zip4j");
        sdkInfoMap.put("cn.bertsir.zbar", "zBarLibary");
        sdkInfoMap.put("com.linfaxin.xmcontainer", "xmcontainer");
        sdkInfoMap.put("com.xk.sup", "xk_sup");
        sdkInfoMap.put("org.xutils", "xUtils");
        sdkInfoMap.put("com.android.volley", "volley");
        sdkInfoMap.put("com.viewpagerindicator", "viewpagerindicator");
        sdkInfoMap.put("com.nostra13.universalimageloader", "universalimageloader");
        sdkInfoMap.put("com.uxin.ulslibrary", "uls");
        sdkInfoMap.put("com.yalantis.ucrop", "uCrop");
        sdkInfoMap.put("com.twitter.sdk.", "twitter");
        sdkInfoMap.put("net.grandcentrix.tray", "tray");
        sdkInfoMap.put("com.termux.app.", "termux");
        sdkInfoMap.put("com.readystatesoftware.systembartint", "systembartint");
        sdkInfoMap.put("com.baoyz.swipemenulistview", "swipemenulistview");
        sdkInfoMap.put("com.tonicartos.widget.stickygridheaders", "stickygridheaders");
        sdkInfoMap.put("com.snappydb", "snappydb");
        sdkInfoMap.put("uk.co.senab.photoview", "senab_photoview");
        sdkInfoMap.put("com.securepreferences", "securepreferences");
        sdkInfoMap.put("com.yqritc.scalablevideoview", "scalablevideoview");
        sdkInfoMap.put("com.makeramen.roundedimageview", "roundedimageview");
        sdkInfoMap.put("org.robobinding", "robobinding");
        sdkInfoMap.put("com.bartoszlipinski.recyclerviewheader", "recyclerviewheader2");
        sdkInfoMap.put("com.facebook.rebound", "rebound");
        sdkInfoMap.put("com.masteratul.exceptionhandler", "react-native异常处理库");
        sdkInfoMap.put("com.handmark.pulltorefresh", "pulltorefresh");
        sdkInfoMap.put("com.squareup.picasso", "picasso");
        sdkInfoMap.put("com.paypal.android.sdk", "paypal");
        sdkInfoMap.put("io.card.payment", "paypal");
        sdkInfoMap.put("com.paypal.android.", "paypal");
        sdkInfoMap.put("com.squareup.otto", "otto");
        sdkInfoMap.put("com.orhanobut.logger", "orhanobut_logger");
        sdkInfoMap.put("com.lk.sdk", "ok");
        sdkInfoMap.put("okhttp3", "okhttp3");
        sdkInfoMap.put("com.squareup.okhttp", "okhttp");
        sdkInfoMap.put("com.nineoldandroids", "nineoldandroids");
        sdkInfoMap.put("com.wang.avi", "music player");
        sdkInfoMap.put("com.github.mikephil.charting", "mikephil_charting");
        sdkInfoMap.put("com.afollestad.materialdialogs", "materialdialogs");
        sdkInfoMap.put("com.wdullaer.materialdatetimepicker", "materialdatetimepicker");
        sdkInfoMap.put("com.luck.picture", "luck_picture");
        sdkInfoMap.put("com.loopj.android.http", "loopj_android-async-http");
        sdkInfoMap.put("org.litepal", "litepal_SQLite");
        sdkInfoMap.put("com.nhaarman.listviewanimations", "listviewanimations");
        sdkInfoMap.put("junit.framework", "junit");
        sdkInfoMap.put("com.firebase.jobdispatcher", "jobdispatcher");
        sdkInfoMap.put("com.joanzapata.pdfview", "joanzapata_pdfview");
        sdkInfoMap.put("com.jeremyfeinstein.slidingmenu.lib", "jeremyfeinstein_slidingmenu");
        sdkInfoMap.put("com.github.javiersantos.piracychecker.", "javiersantos_PiracyChecker");
        sdkInfoMap.put("com.squareup.javapoet", "javapoet");
        sdkInfoMap.put("jackpal.androidterm.Term", "jackpal_androidterm");
        sdkInfoMap.put("jackpal.androidterm", "jackpal_androidterm");
        sdkInfoMap.put("com.ixintui.push", "ixintui 推送");
        sdkInfoMap.put("com.ironsource.sdk.", "ironSource");
        sdkInfoMap.put("de.innosystec.unrar", "innosystec_unrar");
        sdkInfoMap.put("it.sephiroth.android.library.imagezoom", "imagezoom");
        sdkInfoMap.put("com.facebook.cache.common", "image management");
        sdkInfoMap.put("com.facebook.imagepipeline", "image management");
        sdkInfoMap.put("cn.cloudcore.iprotect", "iProtect网银安全服务");
        sdkInfoMap.put("com.nantian.iBank", "iBank");
        sdkInfoMap.put("com.huewu.pla.lib", "huewu_listview");
        sdkInfoMap.put("de.greenrobot.event", "greenEventBus");
        sdkInfoMap.put("de.greenrobot.dao", "greenDAO");
        sdkInfoMap.put("com.facebook.crypto", "facebook_crypto");
        sdkInfoMap.put("com.ms.square.android.expandabletextview", "expandabletextview");
        sdkInfoMap.put("org.simple.eventbus", "eventbus");
        sdkInfoMap.put("com.boc.epay", "epay支付");
        sdkInfoMap.put("com.rockerhieu.emojicon", "emojicon");
        sdkInfoMap.put("com.dropbox.core", "dropbox");
        sdkInfoMap.put("com.dropbox.client2.android", "dropbox");
        sdkInfoMap.put("com.dropbox.sync", "dropbox");
        sdkInfoMap.put("pl.droidsonroids.gif", "displaying animated GIF");
        sdkInfoMap.put("com.facebook.device.yearclass", "device_yearclass");
        sdkInfoMap.put("com.daimajia.numberprogressbar", "daimajia_numberprogressbar");
        sdkInfoMap.put("dagger", "dagger");
        sdkInfoMap.put("com.oasisfeng.condom.", "condom");
        sdkInfoMap.put("org.teleal.cling.", "cling");
        sdkInfoMap.put("shadow.bundletool", "bundletool");
        sdkInfoMap.put("com.bigkoo.convenientbanner", "bigkoo_convenientbanner");
        sdkInfoMap.put("it.sephiroth.android.library", "auto-scroll circular parallax ListViews.");
        sdkInfoMap.put("org.androidannotations.annotations", "androidannotations");
        sdkInfoMap.put("com.andexert.library", "andexert");
        sdkInfoMap.put("org.android.agoo.accs.", "agoo");
        sdkInfoMap.put("org.android.agoo", "agoo");
        sdkInfoMap.put("com.android.agoo.", "agoo");
        sdkInfoMap.put("org.achartengine", "achartengine");
        sdkInfoMap.put("com.stone.zxing.", "ZXing");
        sdkInfoMap.put("com.uuzuche.lib_zxing", "ZXing");
        sdkInfoMap.put("com.zijunlin.zxing", "ZXing");
        sdkInfoMap.put("com.google.zxing", "ZXing");
        sdkInfoMap.put("com.xuexiang.xqrcode.", "XQRCode");
        sdkInfoMap.put("org.xclcharts", "XCL-Charts");
        sdkInfoMap.put("cn.wps.moffice.", "Wps");
        sdkInfoMap.put("com.feinnoui.library.wps.", "Wps");
        sdkInfoMap.put("androidx.work.impl.", "WorkManager");
        sdkInfoMap.put("cn.reactnative.modules.weibo.", "WeiboReactNative");
        sdkInfoMap.put("com.wepayplugin", "WePay");
        sdkInfoMap.put("com.wangyin.wepay", "WePay");
        sdkInfoMap.put("com.kingsoft.mail.", "WPS mail");
        sdkInfoMap.put("com.kingsoft.email", "WPS mail");
        sdkInfoMap.put("com.vungle.warren.", "Vungle CN");
        sdkInfoMap.put("com.vk.sdk", "Vk");
        sdkInfoMap.put("com.vivo.VivoPushMessageReceiver", "Vivo 推送");
        sdkInfoMap.put("com.vivo.push", "Vivo 推送");
        sdkInfoMap.put("io.vov.vitamio", "Vitamio");
        sdkInfoMap.put("io.virtualapp.", "VirtualApp");
        sdkInfoMap.put("com.lody.virtual", "VirtualApp");
        sdkInfoMap.put("com.bartoszlipinski.viewpropertyobjectanimator", "ViewPropertyAnimator");
        sdkInfoMap.put("com.uservoice.uservoicesdk", "UserVoice");
        sdkInfoMap.put("com.unity3d.player", "Unity3d");
        sdkInfoMap.put("unityplayer.UnityActivity", "Unity-UI");
        sdkInfoMap.put("unity.build-id", "Unity-UI");
        sdkInfoMap.put("unityplayer.ForwardNativeEventsToDalvik", "Unity-UI");
        sdkInfoMap.put("com.lostpolygon.unity.", "Unity-UI");
        sdkInfoMap.put("unity.splash-enable", "Unity-UI");
        sdkInfoMap.put("in.srain.cube.views.ptr", "Ultra Pull to Refresh");
        sdkInfoMap.put("com.uc.addon.sdk.remote", "UC插件");
        sdkInfoMap.put("retrofit2", "Type-safe REST client");
        sdkInfoMap.put("com.base.bj.paysdk", "Trpay支付");
        sdkInfoMap.put("com.base.bj.trpayjar", "Trpay支付");
        sdkInfoMap.put("com.transitionseverywhere", "Transitions API");
        sdkInfoMap.put("android.support.transition", "Transitions API");
        sdkInfoMap.put("com.linfaxin.transitionplayer.", "TransitionPlayer");
        sdkInfoMap.put("com.talkingdata.sdk", "Talkingdata");
        sdkInfoMap.put("com.allinpay.", "TODO 通联支付");
        sdkInfoMap.put("com.aspsine.swipetoloadlayout", "SwipeToLoadLayout");
        sdkInfoMap.put("com.baoyz.widget", "SwipeRefreshLayout");
        sdkInfoMap.put("com.daimajia.swipe", "Swipe Layout");
        sdkInfoMap.put("org.swiftp", "SwiFTP");
        sdkInfoMap.put("com.player.sunplayer.", "SunPlayer");
        sdkInfoMap.put("org.jivesoftware.smack", "Smack");
        sdkInfoMap.put("me.leolin.shortcutbadger", "ShortcutBadger");
        sdkInfoMap.put("moe.shizuku.api.", "Shizuku");
        sdkInfoMap.put("moe.shizuku.client.", "Shizuku");
        sdkInfoMap.put("cn.sharesdk", "Share");
        sdkInfoMap.put("com.sensetime.liveness.", "SenseID 身份验证服务");
        sdkInfoMap.put("com.sensetime.idcard", "SenseID 身份验证服务");
        sdkInfoMap.put("com.mob.secverify", "SecVerify");
        sdkInfoMap.put("net.sqlcipher", "SQLCipher");
        sdkInfoMap.put("org.libsdl.", "SDL");
        sdkInfoMap.put("rx.android", "RxJava");
        sdkInfoMap.put("io.realm", "Realm");
        sdkInfoMap.put("org.rajawali3d", "Rajawali");
        sdkInfoMap.put("com.qiniu.android", "Qiniu Resource (Cloud)");
        sdkInfoMap.put("cooperation.qqhotspot.", "QQ看点");
        sdkInfoMap.put("com.android.billingclient.api.ProxyBillingActivity", "ProxyBillingActivity");
        sdkInfoMap.put("com.google.protobuf", "Protocol Buffers");
        sdkInfoMap.put("com.devbrackets.android.playlistcore", "PlaylistCore");
        sdkInfoMap.put("org.piwik.sdk", "Piwik");
        sdkInfoMap.put("net.sourceforge.pinyin4j", "Pinyin4j");
        sdkInfoMap.put("me.maxwin", "Pinterest style ListView");
        sdkInfoMap.put("com.pingplusplus", "Ping++ 支付");
        sdkInfoMap.put("com.uc.paymentsdk.", "Payment");
        sdkInfoMap.put("com.swwx.paymax.", "Paymax支付");
        sdkInfoMap.put("com.liulishuo.okdownload", "OkDownload");
        sdkInfoMap.put("com.j256.ormlite", "ORMLite");
        sdkInfoMap.put("com.coloros.mcssdk", "OPPO 推送");
        sdkInfoMap.put("com.heytap.mcssdk", "OPPO 推送");
        sdkInfoMap.put("com.heytap.msp", "OPPO 推送");
        sdkInfoMap.put("com.synconset.MultiImageChooserActivity", "MultiImageChooser");
        sdkInfoMap.put("com.mob.tools", "Mob 推送");
        sdkInfoMap.put("com.mob.MobProvider", "Mob 推送");
        sdkInfoMap.put("com.mob.pushsdk.", "Mob 推送");
        sdkInfoMap.put("com.microsoft.mmx", "Microsoft mmx");
        sdkInfoMap.put("com.mmx.microsoft.", "Microsoft mmx");
        sdkInfoMap.put("com.microsoft.mmx.feedback", "Microsoft feedback");
        sdkInfoMap.put("com.microsoft.office.feedback.", "Microsoft feedback");
        sdkInfoMap.put("com.microsoft.tokenshare.", "Microsoft TokenShare");
        sdkInfoMap.put("com.microsoft.notes", "Microsoft Notes");
        sdkInfoMap.put("com.microsoft.intune.", "Microsoft Intune");
        sdkInfoMap.put("com.microsoft.identity.", "Microsoft AAD");
        sdkInfoMap.put("com.microsoft.aad.adal", "Microsoft AAD");
        sdkInfoMap.put("org.msgpack", "MessagePack");
        sdkInfoMap.put("me.zhanghai.android.materialprogressbar", "Material design ProgressBar");
        sdkInfoMap.put("com.airbnb.lottie.", "Lottie");
        sdkInfoMap.put("com.live.watermelon", "LivePush");
        sdkInfoMap.put("com.live.sync", "LivePush");
        sdkInfoMap.put("com.live.push", "LivePush");
        sdkInfoMap.put("linkedme.sdk.key", "LinkedMe");
        sdkInfoMap.put("jp.line.sdk", "Line 分享");
        sdkInfoMap.put("com.arrownock.push", "Lightspeed Push");
        sdkInfoMap.put("com.squareup.leakcanary", "LeakCanary");
        sdkInfoMap.put("com.leon.lfilepickerlibrary.", "LFilePicker");
        sdkInfoMap.put("com.kakao.sdk.AppKey", "Kakao Talk");
        sdkInfoMap.put("org.ccil.cowan.tagsoup", "Just Keep On Truckin");
        sdkInfoMap.put("com.jawbone.upplatformsdk.oauth", "Jawbone");
        sdkInfoMap.put("org.eclipse.paho.client.mqttv3", "Java MQTT Client");
        sdkInfoMap.put("com.lzy.imagepicker.", "ImagePicker");
        sdkInfoMap.put("com.imagepicker", "ImagePicker");
        sdkInfoMap.put("com.devsmart", "Horizontal ListView");
        sdkInfoMap.put("net.hockeyapp.android", "HockeyApp");
        sdkInfoMap.put("org.json", "Gson");
        sdkInfoMap.put("com.google.gson", "Gson");
        sdkInfoMap.put("com.growingio.android.sdk", "GrowingIO");
        sdkInfoMap.put("tcking.github.com.giraffeplayer2.", "GiraffePlayer2");
        sdkInfoMap.put("jp.co.cyberagent.android.gpuimage", "GPUImage");
        sdkInfoMap.put("com.foobnix.", "Foobnix");
        sdkInfoMap.put("com.flurry.android", "Flurry");
        sdkInfoMap.put("com.getbase.floatingactionbutton", "Floating Action Button");
        sdkInfoMap.put("com.yhao.floatwindow", "FloatWindow");
        sdkInfoMap.put("com.firebase.ui.", "FirebaseUI");
        sdkInfoMap.put("com.github.developerpaul123.filepickerlibrary.", "FilePickerLibrary");
        sdkInfoMap.put("com.liulishuo.filedownloader", "FileDownloader");
        sdkInfoMap.put("com.facebook.sdk", "Facebook");
        sdkInfoMap.put("com.facebook.FacebookContent", "Facebook");
        sdkInfoMap.put("com.facebook", "Facebook React");
        sdkInfoMap.put("com.facebook.react", "Facebook React");
        sdkInfoMap.put("io.fabric.ApiKey", "Fabric");
        sdkInfoMap.put("com.evernote.android.job.", "Evernote推送");
        sdkInfoMap.put("com.estore.iap.TypaySdkActivity", "Estore iap");
        sdkInfoMap.put("com.rengwuxian.materialedittext", "EditText in Material Design");
        sdkInfoMap.put("pub.devrel.easypermissions", "EasyPermissions");
        sdkInfoMap.put("com.easemob.easeui.ui", "EaseUi");
        sdkInfoMap.put("org.ebookdroid.", "EBookDroid");
        sdkInfoMap.put("com.e4a.runtime", "E4a");
        sdkInfoMap.put("com.ss.android.downloadlib.", "DownloadService");
        sdkInfoMap.put("com.ss.android.socialbase.downloader", "DownloadService");
        sdkInfoMap.put("com.ss.android.socialbase.appdownloader", "DownloadService");
        sdkInfoMap.put("com.doublelabs.", "Double Labs");
        sdkInfoMap.put("com.jakewharton.disklrucache", "Disk-based LRU cache");
        sdkInfoMap.put("com.digits.sdk.android", "Digits");
        sdkInfoMap.put("com.dataeye.channel", "DataEye 统计分析");
        sdkInfoMap.put("io.dcloud.appstream.", "DCloud");
        sdkInfoMap.put("io.dcloud.common", "DCloud");
        sdkInfoMap.put("io.dcloud.streamdownload", "DCloud");
        sdkInfoMap.put("io.dcloud", "DCloud");
        sdkInfoMap.put("cat.ereza.customactivityoncrash.", "CustomActivityOnCrash");
        sdkInfoMap.put("top.zibin.luban", "Curzibn_Luban");
        sdkInfoMap.put("com.crashlytics", "Crashlytics");
        sdkInfoMap.put("com.microsoft.cortana.plugin", "Cortana");
        sdkInfoMap.put("com.microsoft.cortana.clientsdk", "Cortana");
        sdkInfoMap.put("com.microsoft.cortana.services", "Cortana");
        sdkInfoMap.put("com.microsoft.cortana.sdk", "Cortana");
        sdkInfoMap.put("com.microsoft.cortana.", "Cortana");
        sdkInfoMap.put("io.github.pwlin.cordova.plugins.", "Cordova");
        sdkInfoMap.put("org.apache.cordova", "Cordova");
        sdkInfoMap.put("com.chukong.cocosplay", "CocosPlay");
        sdkInfoMap.put("com.wbtech.ums", "Cobub Razor");
        sdkInfoMap.put("com.cloudrail.si", "CloudRail");
        sdkInfoMap.put("at.markushi.ui", "Circle button widget");
        sdkInfoMap.put("com.readystatesoftware.chuck", "Chuck");
        sdkInfoMap.put("org.chromium.base", "Chromium");
        sdkInfoMap.put("com.allenliu.versionchecklib", "CheckVersionLib");
        sdkInfoMap.put("com.diegocarloslima.byakugallery.lib", "ByakuGallery");
        sdkInfoMap.put("com.bugtags.library.", "Bugtag");
        sdkInfoMap.put("com.bugsnag.android.", "Bugsnag");
        sdkInfoMap.put("com.braintreepayments.api.", "Braintree支付");
        sdkInfoMap.put("com.boku.mobile.", "Boku Pay");
        sdkInfoMap.put("cn.bmob.", "Bmob");
        sdkInfoMap.put("com.blankj.utilcode", "Blankj");
        sdkInfoMap.put("com.microsoft.bing.commonlib", "Bing Search API");
        sdkInfoMap.put("com.microsoft.bing.visualsearch", "Bing Search API");
        sdkInfoMap.put("com.microsoft.bingsearchsdk", "Bing Search API");
        sdkInfoMap.put("com.microsoft.bsearchsdk", "Bing Search API");
        sdkInfoMap.put("com.microsoft.bing.", "Bing Search API");
        sdkInfoMap.put("cn.beecloud.", "BeeCloud 支付");
        sdkInfoMap.put("com.amap.api.", "高德");
        sdkInfoMap.put("com.loc.", "高德");
        sdkInfoMap.put("com.autonavi.", "高德");
        sdkInfoMap.put("com.sobot.chat", "智齿客服");
        sdkInfoMap.put("com.iflytek.", "科大讯飞");
        sdkInfoMap.put("com.trustdecision.mobrisk.", "同盾科技");
        sdkInfoMap.put("com.mob.", "Mob");
        sdkInfoMap.put("com.octopus.ad", "章鱼广告");
        sdkInfoMap.put("com.kwad.sdk.", "快手广告1");
        sdkInfoMap.put("com.yxcorp.kuaishou.", "快手广告2");
        sdkInfoMap.put("com.alimm.tanx.", "阿里广告");
        sdkInfoMap.put("com.qumeng.", "趣盟广告");
        sdkInfoMap.put("com.vkyb.kv.kvnepo.core.", "字节");
        sdkInfoMap.put("com.bytedance.", "字节");
        sdkInfoMap.put("com.qq.e.", "广点通广告");
        sdkInfoMap.put("com.android.gdt.qone", "广点通反作弊");
    }

    public static String getInvokerDesc(String stack) {
        if (!TextUtils.isEmpty(stack)) {
            if (sdkInfoMap != null && !sdkInfoMap.isEmpty()) {
                for (Map.Entry<String, String> entry : sdkInfoMap.entrySet()) {
                    if (stack.contains(entry.getKey())) {
                        return entry.getValue();
                    }
                }
            }
        }
        return "App本身";
    }

}
