package com.privacy2345.droidprivacy.util;

import android.content.Intent;
import android.content.IntentFilter;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * 系统广播工具类<br>
 * 1、action中文名称映射<br>
 * 2、模拟发送系统广播
 *
 * @author : zhongjy@2345.com
 */
public class SystemBroadcastUtil {
    public static final Map<String, String> broadcastInfoMap = new HashMap<>();

    /**
     * 部分系统广播会导致模拟器崩溃，该部分广播在模拟时可忽略
     */
    public static final Set<String> crashBroadcastActionSet = new HashSet<>();

    static {
        broadcastInfoMap.put("android.accounts.LOGIN_ACCOUNTS_CHANGED", "登录账户发生变更");
        broadcastInfoMap.put("android.accounts.action.ACCOUNT_REMOVED", "账户被移除");
        broadcastInfoMap.put("android.app.action.ACTION_PASSWORD_CHANGED", "密码已更改");
        broadcastInfoMap.put("android.app.action.ACTION_PASSWORD_EXPIRING", "密码即将过期");
        broadcastInfoMap.put("android.app.action.ACTION_PASSWORD_FAILED", "密码验证失败");
        broadcastInfoMap.put("android.app.action.ACTION_PASSWORD_SUCCEEDED", "密码验证成功");
        broadcastInfoMap.put("android.app.action.ACTION_SHOW_NEW_USER_DISCLAIMER", "显示新用户免责声明");
        broadcastInfoMap.put("android.app.action.AFFILIATED_PROFILE_TRANSFER_OWNERSHIP_COMPLETE", "关联配置文件所有权转移完成");
        broadcastInfoMap.put("android.app.action.APPLICATION_DELEGATION_SCOPES_CHANGED", "应用程序委托范围已更改");
        broadcastInfoMap.put("android.app.action.APP_BLOCK_STATE_CHANGED", "应用程序阻塞状态已更改");
        broadcastInfoMap.put("android.app.action.AUTOMATIC_ZEN_RULE_STATUS_CHANGED", "自动禅模式规则状态已更改");
        broadcastInfoMap.put("android.app.action.BUGREPORT_FAILED", "错误报告失败");
        broadcastInfoMap.put("android.app.action.BUGREPORT_SHARE", "错误报告分享");
        broadcastInfoMap.put("android.app.action.BUGREPORT_SHARING_DECLINED", "错误报告分享被拒绝");
        broadcastInfoMap.put("android.app.action.CLOSE_NOTIFICATION_HANDLER_PANEL", "关闭通知处理面板");
        broadcastInfoMap.put("android.app.action.COMPLIANCE_ACKNOWLEDGEMENT_REQUIRED", "需要合规确认");
        broadcastInfoMap.put("android.app.action.CONSOLIDATED_NOTIFICATION_POLICY_CHANGED", "合并通知政策已更改");
        broadcastInfoMap.put("android.app.action.DATA_SHARING_RESTRICTION_APPLIED", "已应用数据共享限制");
        broadcastInfoMap.put("android.app.action.DATA_SHARING_RESTRICTION_CHANGED", "数据共享限制已更改");
        broadcastInfoMap.put("android.app.action.DEVICE_ADMIN_DISABLED", "设备管理员已禁用");
        broadcastInfoMap.put("android.app.action.DEVICE_ADMIN_DISABLE_REQUESTED", "已请求禁用设备管理员");
        broadcastInfoMap.put("android.app.action.DEVICE_ADMIN_ENABLED", "设备管理员已启用");
        broadcastInfoMap.put("android.app.action.DEVICE_OWNER_CHANGED", "设备所有者已更改");
        broadcastInfoMap.put("android.app.action.DEVICE_POLICY_CONSTANTS_CHANGED", "设备政策常量已更改");
        broadcastInfoMap.put("android.app.action.DEVICE_POLICY_RESOURCE_UPDATED", "设备政策资源已更新");
        broadcastInfoMap.put("android.app.action.INTERRUPTION_FILTER_CHANGED", "中断过滤器已更改");
        broadcastInfoMap.put("android.app.action.INTERRUPTION_FILTER_CHANGED_INTERNAL", "中断过滤器内部已更改");
        broadcastInfoMap.put("android.app.action.LOCK_TASK_ENTERING", "正在进入锁定任务模式");
        broadcastInfoMap.put("android.app.action.LOCK_TASK_EXITING", "正在退出锁定任务模式");
        broadcastInfoMap.put("android.app.action.MANAGED_USER_CREATED", "已创建受管理用户");
        broadcastInfoMap.put("android.app.action.NETWORK_LOGS_AVAILABLE", "网络日志可用");
        broadcastInfoMap.put("android.app.action.NEXT_ALARM_CLOCK_CHANGED", "下一个闹钟已更改");
        broadcastInfoMap.put("android.app.action.NOTIFICATION_CHANNEL_BLOCK_STATE_CHANGED", "通知渠道阻塞状态已更改");
        broadcastInfoMap.put("android.app.action.NOTIFICATION_CHANNEL_GROUP_BLOCK_STATE_CHANGED", "通知渠道组阻塞状态已更改");
        broadcastInfoMap.put("android.app.action.NOTIFICATION_LISTENER_ENABLED_CHANGED", "通知监听器启用状态已更改");
        broadcastInfoMap.put("android.app.action.NOTIFICATION_POLICY_ACCESS_GRANTED_CHANGED", "通知政策访问权限已更改");
        broadcastInfoMap.put("android.app.action.NOTIFICATION_POLICY_CHANGED", "通知政策已更改");
        broadcastInfoMap.put("android.app.action.NOTIFY_PENDING_SYSTEM_UPDATE", "通知待处理的系统更新");
        broadcastInfoMap.put("android.app.action.OPERATION_SAFETY_STATE_CHANGED", "操作安全状态已更改");
        broadcastInfoMap.put("android.app.action.PROFILE_OWNER_CHANGED", "配置文件所有者已更改");
        broadcastInfoMap.put("android.app.action.PROFILE_PROVISIONING_COMPLETE", "配置文件配置完成");
        broadcastInfoMap.put("android.app.action.PROVISIONING_COMPLETED", "配置已完成");
        broadcastInfoMap.put("android.app.action.SCHEDULE_EXACT_ALARM_PERMISSION_STATE_CHANGED", "精确闹钟调度权限状态已更改");
        broadcastInfoMap.put("android.app.action.SECURITY_LOGS_AVAILABLE", "安全日志可用");
        broadcastInfoMap.put("android.app.action.SHOW_NEW_USER_DISCLAIMER", "显示新用户免责声明");
        broadcastInfoMap.put("android.app.action.SYSTEM_UPDATE_POLICY_CHANGED", "系统更新政策已更改");
        broadcastInfoMap.put("android.app.action.TRANSFER_OWNERSHIP_COMPLETE", "所有权转移完成");
        broadcastInfoMap.put("android.app.action.USER_ADDED", "用户已添加");
        broadcastInfoMap.put("android.app.action.USER_REMOVED", "用户已移除");
        broadcastInfoMap.put("android.app.action.USER_STARTED", "用户已启动");
        broadcastInfoMap.put("android.app.action.USER_STOPPED", "用户已停止");
        broadcastInfoMap.put("android.app.action.USER_SWITCHED", "用户已切换");
        broadcastInfoMap.put("android.app.admin.action.DEVICE_FINANCING_STATE_CHANGED", "设备融资状态已更改");
        broadcastInfoMap.put("android.app.admin.action.DEVICE_POLICY_CHANGED", "设备政策已更改");
        broadcastInfoMap.put("android.app.admin.action.DEVICE_POLICY_SET_RESULT", "设备政策设置结果");
        broadcastInfoMap.put("android.appwidget.action.APPWIDGET_DELETED", "应用小部件已删除");
        broadcastInfoMap.put("android.appwidget.action.APPWIDGET_DISABLED", "应用小部件已禁用");
        broadcastInfoMap.put("android.appwidget.action.APPWIDGET_ENABLED", "应用小部件已启用");
        broadcastInfoMap.put("android.appwidget.action.APPWIDGET_ENABLE_AND_UPDATE", "应用小部件已启用并更新");
        broadcastInfoMap.put("android.appwidget.action.APPWIDGET_HOST_RESTORED", "应用小部件宿主已恢复");
        broadcastInfoMap.put("android.appwidget.action.APPWIDGET_RESTORED", "应用小部件已恢复");
        broadcastInfoMap.put("android.appwidget.action.APPWIDGET_UPDATE", "应用小部件已更新");
        broadcastInfoMap.put("android.appwidget.action.APPWIDGET_UPDATE_OPTIONS", "应用小部件更新选项");
        broadcastInfoMap.put("android.bluetooth.a2dp-sink.profile.action.CONNECTION_STATE_CHANGED", "蓝牙A2DP接收端连接状态已更改");
        broadcastInfoMap.put("android.bluetooth.a2dp.profile.action.ACTIVE_DEVICE_CHANGED", "蓝牙A2DP活动设备已更改");
        broadcastInfoMap.put("android.bluetooth.a2dp.profile.action.AVRCP_CONNECTION_STATE_CHANGED", "蓝牙A2DP的AVRCP连接状态已更改");
        broadcastInfoMap.put("android.bluetooth.a2dp.profile.action.CODEC_CONFIG_CHANGED", "蓝牙A2DP编解码器配置已更改");
        broadcastInfoMap.put("android.bluetooth.a2dp.profile.action.CONNECTION_STATE_CHANGED", "蓝牙A2DP连接状态已更改");
        broadcastInfoMap.put("android.bluetooth.a2dp.profile.action.PLAYING_STATE_CHANGED", "蓝牙A2DP播放状态已更改");
        broadcastInfoMap.put("android.bluetooth.action.CSIS_CONNECTION_STATE_CHANGED", "蓝牙CSIS连接状态已更改");
        broadcastInfoMap.put("android.bluetooth.action.LE_AUDIO_ACTIVE_DEVICE_CHANGED", "蓝牙低功耗音频活动设备已更改");
        broadcastInfoMap.put("android.bluetooth.action.LE_AUDIO_CONNECTION_STATE_CHANGED", "蓝牙低功耗音频连接状态已更改");
        broadcastInfoMap.put("android.bluetooth.action.TETHERING_STATE_CHANGED", "蓝牙 tethering 状态已更改");
        broadcastInfoMap.put("android.bluetooth.adapter.action.BLE_ACL_CONNECTED", "蓝牙适配器BLE ACL已连接");
        broadcastInfoMap.put("android.bluetooth.adapter.action.BLE_ACL_DISCONNECTED", "蓝牙适配器BLE ACL已断开连接");
        broadcastInfoMap.put("android.bluetooth.adapter.action.BLE_STATE_CHANGED", "蓝牙适配器BLE状态已更改");
        broadcastInfoMap.put("android.bluetooth.adapter.action.BLUETOOTH_ADDRESS_CHANGED", "蓝牙适配器地址已更改");
        broadcastInfoMap.put("android.bluetooth.adapter.action.CONNECTION_STATE_CHANGED", "蓝牙适配器连接状态已更改");
        broadcastInfoMap.put("android.bluetooth.adapter.action.DISCOVERY_FINISHED", "蓝牙适配器发现已完成");
        broadcastInfoMap.put("android.bluetooth.adapter.action.DISCOVERY_STARTED", "蓝牙适配器发现已开始");
        broadcastInfoMap.put("android.bluetooth.adapter.action.LOCAL_NAME_CHANGED", "蓝牙适配器本地名称已更改");
        broadcastInfoMap.put("android.bluetooth.adapter.action.SCAN_MODE_CHANGED", "蓝牙适配器扫描模式已更改");
        broadcastInfoMap.put("android.bluetooth.adapter.action.STATE_CHANGED", "蓝牙适配器状态已更改");
        broadcastInfoMap.put("android.bluetooth.avrcp-controller.profile.action.CONNECTION_STATE_CHANGED", "蓝牙AVRCP控制器连接状态已更改");
        broadcastInfoMap.put("android.bluetooth.avrcp-controller.profile.action.PLAYER_SETTING", "蓝牙AVRCP控制器播放器设置");
        broadcastInfoMap.put("android.bluetooth.device.action.ACL_CONNECTED", "蓝牙设备ACL已连接");
        broadcastInfoMap.put("android.bluetooth.device.action.ACL_DISCONNECTED", "蓝牙设备ACL已断开连接");
        broadcastInfoMap.put("android.bluetooth.device.action.ACL_DISCONNECT_REQUESTED", "已请求断开蓝牙设备ACL连接");
        broadcastInfoMap.put("android.bluetooth.device.action.ALIAS_CHANGED", "蓝牙设备别名已更改");
        broadcastInfoMap.put("android.bluetooth.device.action.BATTERY_LEVEL_CHANGED", "蓝牙设备电池电量已更改");
        broadcastInfoMap.put("android.bluetooth.device.action.BOND_STATE_CHANGED", "蓝牙设备绑定状态已更改");
        broadcastInfoMap.put("android.bluetooth.device.action.CLASS_CHANGED", "蓝牙设备类别已更改");
        broadcastInfoMap.put("android.bluetooth.device.action.CONNECTION_ACCESS_CANCEL", "蓝牙设备连接访问已取消");
        broadcastInfoMap.put("android.bluetooth.device.action.CONNECTION_ACCESS_REPLY", "蓝牙设备连接访问回复");
        broadcastInfoMap.put("android.bluetooth.device.action.CONNECTION_ACCESS_REQUEST", "蓝牙设备连接访问请求");
        broadcastInfoMap.put("android.bluetooth.device.action.FOUND", "发现蓝牙设备");
        broadcastInfoMap.put("android.bluetooth.device.action.MAS_INSTANCE", "蓝牙设备MAS实例");
        broadcastInfoMap.put("android.bluetooth.device.action.NAME_CHANGED", "蓝牙设备名称已更改");
        broadcastInfoMap.put("android.bluetooth.device.action.NAME_FAILED", "蓝牙设备名称设置失败");
        broadcastInfoMap.put("android.bluetooth.device.action.PAIRING_CANCEL", "蓝牙设备配对已取消");
        broadcastInfoMap.put("android.bluetooth.device.action.PAIRING_REQUEST", "蓝牙设备配对请求");
        broadcastInfoMap.put("android.bluetooth.device.action.SDP_RECORD", "蓝牙设备SDP记录");
        broadcastInfoMap.put("android.bluetooth.device.action.SILENCE_MODE_CHANGED", "蓝牙设备静音模式已更改");
        broadcastInfoMap.put("android.bluetooth.device.action.UUID", "蓝牙设备UUID");
        broadcastInfoMap.put("android.bluetooth.devicepicker.action.DEVICE_SELECTED", "蓝牙设备选择器已选择设备");
        broadcastInfoMap.put("android.bluetooth.devicepicker.action.LAUNCH", "蓝牙设备选择器已启动");
        broadcastInfoMap.put("android.bluetooth.headset.action.HF_INDICATORS_VALUE_CHANGED", "蓝牙耳机HF指示器值已更改");
        broadcastInfoMap.put("android.bluetooth.headset.action.VENDOR_SPECIFIC_HEADSET_EVENT", "蓝牙耳机特定厂商事件");
        broadcastInfoMap.put("android.bluetooth.headset.profile.action.ACTIVE_DEVICE_CHANGED", "蓝牙耳机配置文件活动设备已更改");
        broadcastInfoMap.put("android.bluetooth.headset.profile.action.AUDIO_STATE_CHANGED", "蓝牙耳机配置文件音频状态已更改");
        broadcastInfoMap.put("android.bluetooth.headset.profile.action.CONNECTION_STATE_CHANGED", "蓝牙耳机配置文件连接状态已更改");
        broadcastInfoMap.put("android.bluetooth.headsetclient.profile.action.AG_CALL_CHANGED", "蓝牙耳机客户端配置文件AG呼叫已更改");
        broadcastInfoMap.put("android.bluetooth.headsetclient.profile.action.AG_EVENT", "蓝牙耳机客户端配置文件AG事件");
        broadcastInfoMap.put("android.bluetooth.headsetclient.profile.action.AUDIO_STATE_CHANGED", "蓝牙耳机客户端配置文件音频状态已更改");
        broadcastInfoMap.put("android.bluetooth.headsetclient.profile.action.CONNECTION_STATE_CHANGED", "蓝牙耳机客户端配置文件连接状态已更改");
        broadcastInfoMap.put("android.bluetooth.headsetclient.profile.action.LAST_VTAG", "蓝牙耳机客户端配置文件最后VTAG");
        broadcastInfoMap.put("android.bluetooth.headsetclient.profile.action.RESULT", "蓝牙耳机客户端配置文件结果");
        broadcastInfoMap.put("android.bluetooth.headsetclient.profile.action.VENDOR_SPECIFIC_EVENT", "蓝牙耳机客户端配置文件特定厂商事件");
        broadcastInfoMap.put("android.bluetooth.hearingaid.profile.action.ACTIVE_DEVICE_CHANGED", "蓝牙助听器配置文件活动设备已更改");
        broadcastInfoMap.put("android.bluetooth.hearingaid.profile.action.CONNECTION_STATE_CHANGED", "蓝牙助听器配置文件连接状态已更改");
        broadcastInfoMap.put("android.bluetooth.hearingaid.profile.action.PLAYING_STATE_CHANGED", "蓝牙助听器配置文件播放状态已更改");
        broadcastInfoMap.put("android.bluetooth.hiddevice.profile.action.CONNECTION_STATE_CHANGED", "蓝牙HID设备配置文件连接状态已更改");
        broadcastInfoMap.put("android.bluetooth.input.profile.action.CONNECTION_STATE_CHANGED", "蓝牙输入设备配置文件连接状态已更改");
        broadcastInfoMap.put("android.bluetooth.input.profile.action.HANDSHAKE", "蓝牙输入设备配置文件握手");
        broadcastInfoMap.put("android.bluetooth.input.profile.action.IDLE_TIME_CHANGED", "蓝牙输入设备配置文件空闲时间已更改");
        broadcastInfoMap.put("android.bluetooth.input.profile.action.PROTOCOL_MODE_CHANGED", "蓝牙输入设备配置文件协议模式已更改");
        broadcastInfoMap.put("android.bluetooth.input.profile.action.REPORT", "蓝牙输入设备配置文件报告");
        broadcastInfoMap.put("android.bluetooth.input.profile.action.VIRTUAL_UNPLUG_STATUS", "蓝牙输入设备配置文件虚拟拔出状态");
        broadcastInfoMap.put("android.bluetooth.inputhost.profile.action.CONNECTION_STATE_CHANGED", "蓝牙输入主机配置文件连接状态已更改");
        broadcastInfoMap.put("android.bluetooth.map.profile.action.CONNECTION_STATE_CHANGED", "蓝牙MAP配置文件连接状态已更改");
        broadcastInfoMap.put("android.bluetooth.mapmce.profile.action.CONNECTION_STATE_CHANGED", "蓝牙MAPMCE配置文件连接状态已更改");
        broadcastInfoMap.put("android.bluetooth.mapmce.profile.action.MESSAGE_DELETED_STATUS_CHANGED", "蓝牙MAPMCE配置文件消息删除状态已更改");
        broadcastInfoMap.put("android.bluetooth.mapmce.profile.action.MESSAGE_DELIVERED_SUCCESSFULLY", "蓝牙MAPMCE配置文件消息已成功送达");
        broadcastInfoMap.put("android.bluetooth.mapmce.profile.action.MESSAGE_READ_STATUS_CHANGED", "蓝牙MAPMCE配置文件消息阅读状态已更改");
        broadcastInfoMap.put("android.bluetooth.mapmce.profile.action.MESSAGE_RECEIVED", "蓝牙MAPMCE配置文件已接收消息");
        broadcastInfoMap.put("android.bluetooth.mapmce.profile.action.MESSAGE_SENT_SUCCESSFULLY", "蓝牙MAPMCE配置文件消息已成功发送");
        broadcastInfoMap.put("android.bluetooth.pan.profile.action.CONNECTION_STATE_CHANGED", "蓝牙PAN配置文件连接状态已更改");
        broadcastInfoMap.put("android.bluetooth.pbap.profile.action.CONNECTION_STATE_CHANGED", "蓝牙PBAP配置文件连接状态已更改");
        broadcastInfoMap.put("android.bluetooth.pbapclient.profile.action.CONNECTION_STATE_CHANGED", "蓝牙PBAP客户端配置文件连接状态已更改");
        broadcastInfoMap.put("android.bluetooth.sap.profile.action.CONNECTION_STATE_CHANGED", "蓝牙SAP配置文件连接状态已更改");
        broadcastInfoMap.put("android.companion.virtual.action.VIRTUAL_DEVICE_REMOVED", "虚拟设备已移除");
        broadcastInfoMap.put("android.content.pm.action.SESSION_COMMITTED", "应用会话已提交");
        broadcastInfoMap.put("android.content.pm.action.SESSION_UPDATED", "应用会话已更新");
        broadcastInfoMap.put("android.hardware.action.NEW_PICTURE", "新图片生成");
        broadcastInfoMap.put("android.hardware.action.NEW_VIDEO", "新视频生成");
        broadcastInfoMap.put("android.hardware.hdmi.action.ON_ACTIVE_SOURCE_RECOVERED_DISMISS_UI", "HDMI活动源恢复后关闭UI");
        broadcastInfoMap.put("android.hardware.hdmi.action.OSD_MESSAGE", "HDMI OSD消息");
        broadcastInfoMap.put("android.hardware.input.action.QUERY_KEYBOARD_LAYOUTS", "查询键盘布局");
        broadcastInfoMap.put("android.hardware.usb.action.USB_ACCESSORY_ATTACHED", "USB配件已连接");
        broadcastInfoMap.put("android.hardware.usb.action.USB_ACCESSORY_DETACHED", "USB配件已断开连接");
        broadcastInfoMap.put("android.hardware.usb.action.USB_ACCESSORY_HANDSHAKE", "USB配件握手");
        broadcastInfoMap.put("android.hardware.usb.action.USB_DEVICE_ATTACHED", "USB设备已连接");
        broadcastInfoMap.put("android.hardware.usb.action.USB_DEVICE_DETACHED", "USB设备已断开连接");
        broadcastInfoMap.put("android.intent.action.ACTION_IDLE_MAINTENANCE_END", "空闲维护已结束");
        broadcastInfoMap.put("android.intent.action.ACTION_IDLE_MAINTENANCE_START", "空闲维护已开始");
        broadcastInfoMap.put("android.intent.action.ACTION_POWER_CONNECTED", "电源已连接");
        broadcastInfoMap.put("android.intent.action.ACTION_POWER_DISCONNECTED", "电源已断开连接");
        broadcastInfoMap.put("android.intent.action.ACTION_PREFERRED_ACTIVITY_CHANGED", "首选活动已更改");
        broadcastInfoMap.put("android.intent.action.ACTION_SHUTDOWN", "系统即将关机");
        broadcastInfoMap.put("android.intent.action.AIRPLANE_MODE", "飞行模式状态变化");
        broadcastInfoMap.put("android.intent.action.ALARM_CHANGED", "闹钟已更改");
        broadcastInfoMap.put("android.intent.action.APPLICATION_LOCALE_CHANGED", "应用程序区域设置已更改");
        broadcastInfoMap.put("android.intent.action.APPLICATION_RESTRICTIONS_CHANGED", "应用程序限制已更改");
        broadcastInfoMap.put("android.intent.action.BATTERY_CHANGED", "电池状态已更改");
        broadcastInfoMap.put("android.intent.action.BATTERY_LOW", "电池电量低");
        broadcastInfoMap.put("android.intent.action.BATTERY_OKAY", "电池电量已恢复正常");
        broadcastInfoMap.put("android.intent.action.BOOT_COMPLETED", "系统启动完成");
        broadcastInfoMap.put("android.intent.action.CALL_DISCONNECT_CAUSE", "呼叫断开原因");
        broadcastInfoMap.put("android.intent.action.CAMERA_BUTTON", "相机按键事件");
        broadcastInfoMap.put("android.intent.action.CANCEL_ENABLE_ROLLBACK", "取消启用回滚");
        broadcastInfoMap.put("android.intent.action.CLEAR_DNS_CACHE", "清除DNS缓存");
        broadcastInfoMap.put("android.intent.action.CLOSE_SYSTEM_DIALOGS", "关闭系统对话框");
        broadcastInfoMap.put("android.intent.action.CONFIGURATION_CHANGED", "配置已更改");
        broadcastInfoMap.put("android.intent.action.CONTENT_CHANGED", "内容已更改");
        broadcastInfoMap.put("android.intent.action.DATA_SMS_RECEIVED", "已接收数据短信");
        broadcastInfoMap.put("android.intent.action.DATA_STALL_DETECTED", "检测到数据停滞");
        broadcastInfoMap.put("android.intent.action.DATE_CHANGED", "日期已更改");
        broadcastInfoMap.put("android.intent.action.DEVICE_STORAGE_FULL", "设备存储已满");
        broadcastInfoMap.put("android.intent.action.DEVICE_STORAGE_LOW", "设备存储不足");
        broadcastInfoMap.put("android.intent.action.DEVICE_STORAGE_NOT_FULL", "设备存储未满");
        broadcastInfoMap.put("android.intent.action.DEVICE_STORAGE_OK", "设备存储状态正常");
        broadcastInfoMap.put("android.intent.action.DISTRACTING_PACKAGES_CHANGED", "干扰性应用包已更改");
        broadcastInfoMap.put("android.intent.action.DOCK_EVENT", "底座事件");
        broadcastInfoMap.put("android.intent.action.DOMAINS_NEED_VERIFICATION", "域名需要验证");
        broadcastInfoMap.put("android.intent.action.DOWNLOAD_COMPLETE", "下载已完成");
        broadcastInfoMap.put("android.intent.action.DOWNLOAD_NOTIFICATION_CLICKED", "下载通知已点击");
        broadcastInfoMap.put("android.intent.action.DREAMING_STARTED", "屏保已启动");
        broadcastInfoMap.put("android.intent.action.DREAMING_STOPPED", "屏保已停止");
        broadcastInfoMap.put("android.intent.action.DROPBOX_ENTRY_ADDED", "Dropbox条目已添加");
        broadcastInfoMap.put("android.intent.action.DYNAMIC_SENSOR_CHANGED", "动态传感器已更改");
        broadcastInfoMap.put("android.intent.action.EMERGENCY_CALLBACK_MODE_CHANGED", "紧急呼叫回调模式已更改");
        broadcastInfoMap.put("android.intent.action.EMERGENCY_CALL_STATE_CHANGED", "紧急呼叫状态已更改");
        broadcastInfoMap.put("android.intent.action.EXTERNAL_APPLICATIONS_AVAILABLE", "外部应用程序可用");
        broadcastInfoMap.put("android.intent.action.EXTERNAL_APPLICATIONS_UNAVAILABLE", "外部应用程序不可用");
        broadcastInfoMap.put("android.intent.action.FACTORY_RESET", "恢复出厂设置");
        broadcastInfoMap.put("android.intent.action.FETCH_VOICEMAIL", "获取语音信箱");
        broadcastInfoMap.put("android.intent.action.GTALK_CONNECTED", "GTalk已连接");
        broadcastInfoMap.put("android.intent.action.GTALK_DISCONNECTED", "GTalk已断开连接");
        broadcastInfoMap.put("android.intent.action.HEADSET_PLUG", "耳机插拔事件");
        broadcastInfoMap.put("android.intent.action.INPUT_METHOD_CHANGED", "输入法已更改");
        broadcastInfoMap.put("android.intent.action.INTENT_FILTER_NEEDS_VERIFICATION", "意图过滤器需要验证");
        broadcastInfoMap.put("android.intent.action.LOCALE_CHANGED", "系统区域设置已更改");
        broadcastInfoMap.put("android.intent.action.LOCKED_BOOT_COMPLETED", "锁定状态下启动完成");
        broadcastInfoMap.put("android.intent.action.MAIN_USER_LOCKSCREEN_KNOWLEDGE_FACTOR_CHANGED", "主用户锁屏验证方式已更改");
        broadcastInfoMap.put("android.intent.action.MANAGE_PACKAGE_STORAGE", "管理应用存储");
        broadcastInfoMap.put("android.intent.action.MASTER_CLEAR_NOTIFICATION", "恢复出厂设置通知");
        broadcastInfoMap.put("android.intent.action.MEDIA_BAD_REMOVAL", "存储介质被意外移除");
        broadcastInfoMap.put("android.intent.action.MEDIA_BUTTON", "媒体按键事件");
        broadcastInfoMap.put("android.intent.action.MEDIA_CHECKING", "正在检查存储介质");
        broadcastInfoMap.put("android.intent.action.MEDIA_EJECT", "存储介质被弹出");
        broadcastInfoMap.put("android.intent.action.MEDIA_MOUNTED", "存储介质已挂载");
        broadcastInfoMap.put("android.intent.action.MEDIA_NOFS", "存储介质不支持文件系统");
        broadcastInfoMap.put("android.intent.action.MEDIA_REMOVED", "存储介质已移除");
        broadcastInfoMap.put("android.intent.action.MEDIA_SCANNER_FINISHED", "媒体扫描已完成");
        broadcastInfoMap.put("android.intent.action.MEDIA_SCANNER_SCAN_FILE", "媒体扫描器扫描文件");
        broadcastInfoMap.put("android.intent.action.MEDIA_SCANNER_STARTED", "媒体扫描已开始");
        broadcastInfoMap.put("android.intent.action.MEDIA_SHARED", "存储介质已共享");
        broadcastInfoMap.put("android.intent.action.MEDIA_UNMOUNTABLE", "存储介质无法卸载");
        broadcastInfoMap.put("android.intent.action.MEDIA_UNMOUNTED", "存储介质已卸载");
        broadcastInfoMap.put("android.intent.action.MY_PACKAGE_REPLACED", "当前应用已被替换");
        broadcastInfoMap.put("android.intent.action.MY_PACKAGE_SUSPENDED", "当前应用已被暂停");
        broadcastInfoMap.put("android.intent.action.MY_PACKAGE_UNSUSPENDED", "当前应用已解除暂停");
        broadcastInfoMap.put("android.intent.action.NEW_OUTGOING_CALL", "新的呼出电话");
        broadcastInfoMap.put("android.intent.action.NEW_VOICEMAIL", "新的语音信箱");
        broadcastInfoMap.put("android.intent.action.PACKAGES_SUSPENDED", "应用包已被暂停");
        broadcastInfoMap.put("android.intent.action.PACKAGES_SUSPENSION_CHANGED", "应用包暂停状态已更改");
        broadcastInfoMap.put("android.intent.action.PACKAGES_UNSUSPENDED", "应用包已解除暂停");
        broadcastInfoMap.put("android.intent.action.PACKAGE_ADDED", "应用包已添加");
        broadcastInfoMap.put("android.intent.action.PACKAGE_CHANGED", "应用包已更改");
        broadcastInfoMap.put("android.intent.action.PACKAGE_DATA_CLEARED", "应用包数据已清除");
        broadcastInfoMap.put("android.intent.action.PACKAGE_ENABLE_ROLLBACK", "应用包启用回滚");
        broadcastInfoMap.put("android.intent.action.PACKAGE_FIRST_LAUNCH", "应用包首次启动");
        broadcastInfoMap.put("android.intent.action.PACKAGE_FULLY_REMOVED", "应用包已完全移除");
        broadcastInfoMap.put("android.intent.action.PACKAGE_INSTALL", "应用包安装");
        broadcastInfoMap.put("android.intent.action.PACKAGE_NEEDS_INTEGRITY_VERIFICATION", "应用包需要完整性验证");
        broadcastInfoMap.put("android.intent.action.PACKAGE_NEEDS_VERIFICATION", "应用包需要验证");
        broadcastInfoMap.put("android.intent.action.PACKAGE_REMOVED", "应用包已移除");
        broadcastInfoMap.put("android.intent.action.PACKAGE_REMOVED_INTERNAL", "应用包内部已移除");
        broadcastInfoMap.put("android.intent.action.PACKAGE_REPLACED", "应用包已替换");
        broadcastInfoMap.put("android.intent.action.PACKAGE_RESTARTED", "应用包已重启");
        broadcastInfoMap.put("android.intent.action.PACKAGE_UNSTOPPED", "应用包已解除停止");
        broadcastInfoMap.put("android.intent.action.PACKAGE_UNSUSPENDED_MANUALLY", "应用包已手动解除暂停");
        broadcastInfoMap.put("android.intent.action.PACKAGE_VERIFIED", "应用包已验证");
        broadcastInfoMap.put("android.intent.action.PHONE_STATE", "电话状态");
        broadcastInfoMap.put("android.intent.action.PRECISE_CALL_STATE", "精确通话状态");
        broadcastInfoMap.put("android.intent.action.PRECISE_DATA_CONNECTION_STATE_CHANGED", "精确数据连接状态已更改");
        broadcastInfoMap.put("android.intent.action.PROFILE_ADDED", "配置文件已添加");
        broadcastInfoMap.put("android.intent.action.PROFILE_REMOVED", "配置文件已移除");
        broadcastInfoMap.put("android.intent.action.PROVIDER_CHANGED", "内容提供者已更改");
        broadcastInfoMap.put("android.intent.action.PROXY_CHANGE", "代理设置已更改");
        broadcastInfoMap.put("android.intent.action.QUERY_PACKAGE_RESTART", "查询应用包重启");
        broadcastInfoMap.put("android.intent.action.REBOOT", "设备重启");
        broadcastInfoMap.put("android.intent.action.ROLLBACK_COMMITTED", "回滚已提交");
        broadcastInfoMap.put("android.intent.action.SCREEN_OFF", "屏幕已关闭");
        broadcastInfoMap.put("android.intent.action.SCREEN_ON", "屏幕已开启");
        broadcastInfoMap.put("android.intent.action.SERVICE_STATE", "服务状态");
        broadcastInfoMap.put("android.intent.action.SIM_STATE_CHANGED", "SIM卡状态已更改");
        broadcastInfoMap.put("android.intent.action.SPLIT_CONFIGURATION_CHANGED", "分屏配置已更改");
        broadcastInfoMap.put("android.intent.action.SUB_DEFAULT_CHANGED", "子默认设置已更改");
        broadcastInfoMap.put("android.intent.action.TIMEZONE_CHANGED", "时区已更改");
        broadcastInfoMap.put("android.intent.action.TIME_SET", "时间已设置");
        broadcastInfoMap.put("android.intent.action.TIME_TICK", "时间滴答事件（每分钟触发）");
        broadcastInfoMap.put("android.intent.action.UID_REMOVED", "用户ID已移除");
        broadcastInfoMap.put("android.intent.action.UMS_CONNECTED", "USB存储已连接");
        broadcastInfoMap.put("android.intent.action.UMS_DISCONNECTED", "USB存储已断开连接");
        broadcastInfoMap.put("android.intent.action.UNARCHIVE_PACKAGE", "应用包解压缩");
        broadcastInfoMap.put("android.intent.action.USER_PRESENT", "用户已解锁屏幕");
        broadcastInfoMap.put("android.intent.action.USER_UNLOCKED", "用户已解锁");
        broadcastInfoMap.put("android.intent.action.WALLPAPER_CHANGED", "壁纸已更改");
        broadcastInfoMap.put("android.location.MODE_CHANGED", "位置模式已更改");
        broadcastInfoMap.put("android.location.PROVIDERS_CHANGED", "位置提供者已更改");
        broadcastInfoMap.put("android.location.action.ADAS_GNSS_ENABLED_CHANGED", "ADAS GNSS启用状态已更改");
        broadcastInfoMap.put("android.location.action.GNSS_CAPABILITIES_CHANGED", "GNSS功能已更改");
        broadcastInfoMap.put("android.media.ACTION_SCO_AUDIO_STATE_UPDATED", "SCO音频状态已更新");
        broadcastInfoMap.put("android.media.AUDIO_BECOMING_NOISY", "音频即将变得嘈杂");
        broadcastInfoMap.put("android.media.INTERNAL_RINGER_MODE_CHANGED_ACTION", "内部铃声模式已更改");
        broadcastInfoMap.put("android.media.MASTER_MUTE_CHANGED_ACTION", "主静音状态已更改");
        broadcastInfoMap.put("android.media.RINGER_MODE_CHANGED", "铃声模式已更改");
        broadcastInfoMap.put("android.media.SCO_AUDIO_STATE_CHANGED", "SCO音频状态已更改");
        broadcastInfoMap.put("android.media.STREAM_DEVICES_CHANGED_ACTION", "流设备已更改");
        broadcastInfoMap.put("android.media.STREAM_MUTE_CHANGED_ACTION", "流静音状态已更改");
        broadcastInfoMap.put("android.media.VIBRATE_SETTING_CHANGED", "振动设置已更改");
        broadcastInfoMap.put("android.media.VOLUME_CHANGED_ACTION", "音量已更改");
        broadcastInfoMap.put("android.media.action.CLOSE_AUDIO_EFFECT_CONTROL_SESSION", "关闭音频效果控制会话");
        broadcastInfoMap.put("android.media.action.HDMI_AUDIO_PLUG", "HDMI音频插拔事件");
        broadcastInfoMap.put("android.media.action.MICROPHONE_MUTE_CHANGED", "麦克风静音状态已更改");
        broadcastInfoMap.put("android.media.action.OPEN_AUDIO_EFFECT_CONTROL_SESSION", "打开音频效果控制会话");
        broadcastInfoMap.put("android.media.action.SPEAKERPHONE_STATE_CHANGED", "扬声器状态已更改");
        broadcastInfoMap.put("android.media.tv.action.CHANNEL_BROWSABLE_REQUESTED", "请求频道可浏览");
        broadcastInfoMap.put("android.media.tv.action.INITIALIZE_PROGRAMS", "初始化电视节目");
        broadcastInfoMap.put("android.media.tv.action.PREVIEW_PROGRAM_ADDED_TO_WATCH_NEXT", "预览节目已添加到待看列表");
        broadcastInfoMap.put("android.media.tv.action.PREVIEW_PROGRAM_BROWSABLE_DISABLED", "预览节目可浏览状态已禁用");
        broadcastInfoMap.put("android.media.tv.action.WATCH_NEXT_PROGRAM_BROWSABLE_DISABLED", "待看节目可浏览状态已禁用");
        broadcastInfoMap.put("android.net.action.CLEAR_DNS_CACHE", "清除DNS缓存");
        broadcastInfoMap.put("android.net.conn.BACKGROUND_DATA_SETTING_CHANGED", "后台数据设置已更改");
        broadcastInfoMap.put("android.net.conn.CAPTIVE_PORTAL_TEST_COMPLETED", " captive portal测试已完成");
        broadcastInfoMap.put("android.net.conn.CONNECTIVITY_CHANGE", "网络连接状态已更改");
        broadcastInfoMap.put("android.net.conn.DATA_ACTIVITY_CHANGE", "数据活动状态已更改");
        broadcastInfoMap.put("android.net.conn.INET_CONDITION_ACTION", "网络条件动作");
        broadcastInfoMap.put("android.net.conn.RESTRICT_BACKGROUND_CHANGED", "后台限制已更改");
        broadcastInfoMap.put("android.net.conn.TETHER_STATE_CHANGED", "网络共享状态已更改");
        broadcastInfoMap.put("android.net.nsd.STATE_CHANGED", "网络服务发现状态已更改");
        broadcastInfoMap.put("android.net.scoring.SCORER_CHANGED", "网络评分器已更改");
        broadcastInfoMap.put("android.net.scoring.SCORE_NETWORKS", "网络评分");
        broadcastInfoMap.put("android.net.sip.action.SIP_CALL_OPTION_CHANGED", "SIP通话选项已更改");
        broadcastInfoMap.put("android.net.sip.action.SIP_INCOMING_CALL", "SIP来电");
        broadcastInfoMap.put("android.net.sip.action.SIP_REMOVE_PROFILE", "移除SIP配置文件");
        broadcastInfoMap.put("android.net.sip.action.SIP_SERVICE_UP", "SIP服务已启动");
        broadcastInfoMap.put("android.net.sip.action.START_SIP", "启动SIP");
        broadcastInfoMap.put("android.net.wifi.BATCHED_RESULTS", "WiFi批量结果");
        broadcastInfoMap.put("android.net.wifi.NETWORK_IDS_CHANGED", "WiFi网络ID已更改");
        broadcastInfoMap.put("android.net.wifi.RSSI_CHANGED", "WiFi信号强度已更改");
        broadcastInfoMap.put("android.net.wifi.SCAN_RESULTS", "WiFi扫描结果");
        broadcastInfoMap.put("android.net.wifi.STATE_CHANGE", "WiFi连接状态已更改");
        broadcastInfoMap.put("android.net.wifi.WIFI_STATE_CHANGED", "WiFi状态已更改");
        broadcastInfoMap.put("android.net.wifi.action.WIFI_NETWORK_SUGGESTION_POST_CONNECTION", "WiFi网络建议连接后");
        broadcastInfoMap.put("android.net.wifi.action.WIFI_SCAN_AVAILABILITY_CHANGED", "WiFi扫描可用性已更改");
        broadcastInfoMap.put("android.net.wifi.aware.action.WIFI_AWARE_RESOURCE_CHANGED", "WiFi感知资源已更改");
        broadcastInfoMap.put("android.net.wifi.aware.action.WIFI_AWARE_STATE_CHANGED", "WiFi感知状态已更改");
        broadcastInfoMap.put("android.net.wifi.p2p.CONNECTION_STATE_CHANGE", "WiFi直连连接状态已更改");
        broadcastInfoMap.put("android.net.wifi.p2p.DISCOVERY_STATE_CHANGE", "WiFi直连发现状态已更改");
        broadcastInfoMap.put("android.net.wifi.p2p.PEERS_CHANGED", "WiFi直连对等设备已更改");
        broadcastInfoMap.put("android.net.wifi.p2p.STATE_CHANGED", "WiFi直连状态已更改");
        broadcastInfoMap.put("android.net.wifi.p2p.THIS_DEVICE_CHANGED", "WiFi直连本设备信息已更改");
        broadcastInfoMap.put("android.net.wifi.p2p.action.WIFI_P2P_LISTEN_STATE_CHANGED", "WiFi直连监听状态已更改");
        broadcastInfoMap.put("android.net.wifi.rtt.action.WIFI_RTT_STATE_CHANGED", "WiFi RTT状态已更改");
        broadcastInfoMap.put("android.net.wifi.supplicant.CONNECTION_CHANGE", "WiFi supplicant连接已更改");
        broadcastInfoMap.put("android.net.wifi.supplicant.STATE_CHANGE", "WiFi supplicant状态已更改");
        broadcastInfoMap.put("android.nfc.action.ADAPTER_STATE_CHANGED", "NFC适配器状态已更改");
        broadcastInfoMap.put("android.nfc.action.PREFERRED_PAYMENT_CHANGED", "首选NFC支付方式已更改");
        broadcastInfoMap.put("android.nfc.action.TRANSACTION_DETECTED", "检测到NFC交易");
        broadcastInfoMap.put("android.os.action.ACTION_EFFECTS_SUPPRESSOR_CHANGED", "效果抑制器已更改");
        broadcastInfoMap.put("android.os.action.DEVICE_IDLE_MODE_CHANGED", "设备空闲模式已更改");
        broadcastInfoMap.put("android.os.action.ENHANCED_DISCHARGE_PREDICTION_CHANGED", "增强型放电预测已更改");
        broadcastInfoMap.put("android.os.action.LIGHT_DEVICE_IDLE_MODE_CHANGED", "轻度设备空闲模式已更改");
        broadcastInfoMap.put("android.os.action.LOW_POWER_STANDBY_ENABLED_CHANGED", "低功耗待机启用状态已更改");
        broadcastInfoMap.put("android.os.action.LOW_POWER_STANDBY_POLICY_CHANGED", "低功耗待机策略已更改");
        broadcastInfoMap.put("android.os.action.LOW_POWER_STANDBY_PORTS_CHANGED", "低功耗待机端口已更改");
        broadcastInfoMap.put("android.os.action.POWER_SAVE_MODE_CHANGED", "省电模式已更改");
        broadcastInfoMap.put("android.os.action.POWER_SAVE_MODE_CHANGED_INTERNAL", "省电模式内部已更改");
        broadcastInfoMap.put("android.os.action.POWER_SAVE_MODE_CHANGING", "省电模式正在更改");
        broadcastInfoMap.put("android.os.action.POWER_SAVE_TEMP_WHITELIST_CHANGED", "省电临时白名单已更改");
        broadcastInfoMap.put("android.os.action.POWER_SAVE_WHITELIST_CHANGED", "省电白名单已更改");
        broadcastInfoMap.put("android.os.action.UPDATE_CONFIG", "更新配置");
        broadcastInfoMap.put("android.os.action.UPDATE_EMERGENCY_NUMBER_DB", "更新紧急号码数据库");
        broadcastInfoMap.put("android.provider.Telephony.MMS_DOWNLOADED", "MMS已下载");
        broadcastInfoMap.put("android.provider.Telephony.SECRET_CODE", "Telephony秘密代码");
        broadcastInfoMap.put("android.provider.Telephony.SIM_FULL", "SIM卡存储已满");
        broadcastInfoMap.put("android.provider.Telephony.SMS_CARRIER_PROVISION", "运营商SMS配置");
        broadcastInfoMap.put("android.provider.Telephony.SMS_CB_RECEIVED", "已接收小区广播SMS");
        broadcastInfoMap.put("android.provider.Telephony.SMS_DELIVER", "SMS已送达");
        broadcastInfoMap.put("android.provider.Telephony.SMS_EMERGENCY_CB_RECEIVED", "已接收紧急小区广播SMS");
        broadcastInfoMap.put("android.provider.Telephony.SMS_RECEIVED", "已接收SMS");
        broadcastInfoMap.put("android.provider.Telephony.SMS_REJECTED", "SMS已被拒绝");
        broadcastInfoMap.put("android.provider.Telephony.SMS_SERVICE_CATEGORY_PROGRAM_DATA_RECEIVED", "已接收SMS服务类别程序数据");
        broadcastInfoMap.put("android.provider.Telephony.WAP_PUSH_DELIVER", "WAP推送已送达");
        broadcastInfoMap.put("android.provider.Telephony.WAP_PUSH_RECEIVED", "已接收WAP推送");
        broadcastInfoMap.put("android.provider.action.DEFAULT_SMS_PACKAGE_CHANGED", "默认SMS应用包已更改");
        broadcastInfoMap.put("android.provider.action.DEFAULT_SMS_PACKAGE_CHANGED_INTERNAL", "默认SMS应用包内部已更改");
        broadcastInfoMap.put("android.provider.action.EXTERNAL_PROVIDER_CHANGE", "外部内容提供者已更改");
        broadcastInfoMap.put("android.provider.action.SIM_ACCOUNTS_CHANGED", "SIM卡账户已更改");
        broadcastInfoMap.put("android.provider.action.SMS_EMERGENCY_CB_RECEIVED", "已接收紧急小区广播SMS");
        broadcastInfoMap.put("android.provider.action.SMS_MMS_DB_CREATED", "SMS/MMS数据库已创建");
        broadcastInfoMap.put("android.provider.action.SMS_MMS_DB_LOST", "SMS/MMS数据库已丢失");
        broadcastInfoMap.put("android.provider.action.SYNC_VOICEMAIL", "同步语音信箱");
        broadcastInfoMap.put("android.scheduling.action.REBOOT_READY", "重启准备就绪");
        broadcastInfoMap.put("android.se.omapi.action.SECURE_ELEMENT_STATE_CHANGED", "安全元素状态已更改");
        broadcastInfoMap.put("android.security.STORAGE_CHANGED", "安全存储已更改");
        broadcastInfoMap.put("android.security.action.KEYCHAIN_CHANGED", "密钥链已更改");
        broadcastInfoMap.put("android.security.action.KEY_ACCESS_CHANGED", "密钥访问权限已更改");
        broadcastInfoMap.put("android.security.action.TRUST_STORE_CHANGED", "信任存储已更改");
        broadcastInfoMap.put("android.service.controls.action.ADD_CONTROL", "添加控制服务");
        broadcastInfoMap.put("android.settings.ENABLE_MMS_DATA_REQUEST", "请求启用MMS数据");
        broadcastInfoMap.put("android.settings.SHOW_RESTRICTED_SETTING_DIALOG", "显示受限设置对话框");
        broadcastInfoMap.put("android.speech.tts.TTS_QUEUE_PROCESSING_COMPLETED", "TTS队列处理完成");
        broadcastInfoMap.put("android.speech.tts.engine.TTS_DATA_INSTALLED", "TTS数据已安装");
        broadcastInfoMap.put("android.telephony.action.AREA_INFO_UPDATED", "区域信息已更新");
        broadcastInfoMap.put("android.telephony.action.CARRIER_SIGNAL_DEFAULT_NETWORK_AVAILABLE", "运营商信号默认网络可用");
        broadcastInfoMap.put("android.telephony.action.CARRIER_SIGNAL_PCO_VALUE", "运营商信号PCO值");
        broadcastInfoMap.put("android.telephony.action.CARRIER_SIGNAL_REDIRECTED", "运营商信号已重定向");
        broadcastInfoMap.put("android.telephony.action.CARRIER_SIGNAL_REQUEST_NETWORK_FAILED", "运营商信号请求网络失败");
        broadcastInfoMap.put("android.telephony.action.CARRIER_SIGNAL_RESET", "运营商信号已重置");
        broadcastInfoMap.put("android.telephony.action.DEFAULT_SMS_SUBSCRIPTION_CHANGED", "默认SMS订阅已更改");
        broadcastInfoMap.put("android.telephony.action.DEFAULT_SUBSCRIPTION_CHANGED", "默认订阅已更改");
        broadcastInfoMap.put("android.telephony.action.PRIMARY_SUBSCRIPTION_LIST_CHANGED", "主要订阅列表已更改");
        broadcastInfoMap.put("android.telephony.action.REFRESH_SUBSCRIPTION_PLANS", "刷新订阅计划");
        broadcastInfoMap.put("android.telephony.action.SECRET_CODE", "Telephony秘密代码");
        broadcastInfoMap.put("android.telephony.action.SERVICE_PROVIDERS_UPDATED", "服务提供商已更新");
        broadcastInfoMap.put("android.telephony.action.SIM_APPLICATION_STATE_CHANGED", "SIM卡应用状态已更改");
        broadcastInfoMap.put("android.telephony.action.SIM_CARD_STATE_CHANGED", "SIM卡状态已更改");
        broadcastInfoMap.put("android.telephony.action.SIM_SLOT_STATUS_CHANGED", "SIM卡插槽状态已更改");
        broadcastInfoMap.put("android.telephony.action.SUBSCRIPTION_CARRIER_IDENTITY_CHANGED", "订阅运营商标识已更改");
        broadcastInfoMap.put("android.telephony.action.SUBSCRIPTION_PLANS_CHANGED", "订阅计划已更改");
        broadcastInfoMap.put("android.telephony.action.SUBSCRIPTION_SPECIFIC_CARRIER_IDENTITY_CHANGED", "特定订阅运营商标识已更改");
        broadcastInfoMap.put("android.telephony.euicc.action.NOTIFY_CARRIER_SETUP_INCOMPLETE", "通知运营商设置不完整");
        broadcastInfoMap.put("android.telephony.euicc.action.OTA_STATUS_CHANGED", "eUICC OTA状态已更改");
        broadcastInfoMap.put("android.telephony.ims.action.RCS_SINGLE_REGISTRATION_CAPABILITY_UPDATE", "RCS单一注册能力已更新");
        broadcastInfoMap.put("android.telephony.ims.action.WFC_IMS_REGISTRATION_ERROR", "WFC IMS注册错误");
        broadcastInfoMap.put("com.android.intent.action.DISMISS_KEYBOARD_SHORTCUTS", "关闭键盘快捷键");
        broadcastInfoMap.put("com.android.intent.action.SHOW_KEYBOARD_SHORTCUTS", "显示键盘快捷键");
        broadcastInfoMap.put("com.android.internal.intent.action.ACTION_FORBIDDEN_NO_SERVICE_AUTHORIZATION", "禁止操作：无服务授权");
        broadcastInfoMap.put("com.android.internal.provider.action.VOICEMAIL_SMS_RECEIVED", "已接收语音信箱SMS");

        crashBroadcastActionSet.add("android.media.STREAM_DEVICES_CHANGED_ACTION");
        crashBroadcastActionSet.add("android.intent.action.SERVICE_STATE");
    }

    public static String getSystemBroadcastAction(Object object) {
        if (object instanceof IntentFilter) {
            IntentFilter filter = (IntentFilter) object;
            List<String> actionList = new ArrayList<>();
            for (int i = 0; i < filter.countActions(); i++) {
                String action = filter.getAction(i);
                if (broadcastInfoMap.containsKey(action)) {
                    actionList.add(filter.getAction(i) + ":" + broadcastInfoMap.get(action));
                }
            }
            if (!actionList.isEmpty()) {
                return actionList.toString();
            }
        } else if (object instanceof Intent) {
            Intent intent = (Intent) object;
            if (broadcastInfoMap.containsKey(intent.getAction())) {
                return intent.getAction() + ":" + broadcastInfoMap.get(intent.getAction());
            }
        } else {
            return StringHelper.convertToString(object);
        }
        return null;
    }
}
